include ayu_mirage.conf

font_family		family="JetBrainsMono Nerd Font"
bold_font		auto
italic_font		auto
bold_italic_font	auto
font_size		12

#single_window_padding_width	-1
#window_padding_width		8
placement_strategy		center

remember_window_size  no
initial_window_width  144c
initial_window_height 36c

enable_audio_bell	no
window_alert_on_bell	yes

background_opacity	0.90
background		#222222

tab_bar_style	separator
tab_separator	" || "
tab_bar_align	center
